// src/lib/components/hero/hero.svelte
<script lang="ts">
	import { Section } from '$lib';
	import Typewriter from 'svelte-typewriter';
	import { Button, buttonVariants } from '$lib';
	import { toast } from 'svelte-sonner';
	import type { HTMLAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';
	type $$Props = HTMLAttributes<HTMLDivElement>;
	let className: $$Props['class'] = undefined;
	export { className as class };

	function calendly() {
		window.open('https://calendly.com/xavierloeraflores/30min', '_blank');
		toast('🎉 🎉 🎉 Opening Calendly 🎉 🎉 🎉');
	}
	function resume() {
		toast('🎉 🎉 🎉 Downloading Resume 🎉 🎉 🎉');
	}
</script>

<Section title="">
	<div class={cn('flex h-screen flex-col items-center justify-center p-4', className)}>
		<span
			class="scroll-m-20 pb-2 text-2xl font-semibold tracking-tight text-primary first:mt-0 lg:text-4xl"
			>Hi, my name is</span
		>
		<h1
			class=" scroll-m-20 text-4xl font-extrabold tracking-tight text-secondary-foreground lg:text-7xl"
		>
			<Typewriter>Xavier Loera Flores</Typewriter>
		</h1>
		<h2
			class="scroll-m-20 pb-2 text-3xl font-semibold tracking-tight text-accent-foreground first:mt-0 lg:text-5xl"
		>
			I write software.
		</h2>
		<p
			class="mt-4 w-2/3 max-w-[750px] text-center text-2xl leading-7 text-muted-foreground sm:w-11/12 lg:max-w-[1200px] lg:text-3xl [&:not(:first-child)]:mt-6"
		>
			I am a versatile software engineer and AI innovator, with 3+ years of experience and expertise
			in building scalable, AI-driven platforms. As the co-founder and CTO of Custodia AI, I worked
			on the creation of award-winning applications and empowered small businesses with custom AI
			solutions.
		</p>
		<div class="mt-4 flex flex-row">
			<Button on:click={calendly} class="mx-4">Get in touch</Button>
			<a
				href="/files/resume.pdf"
				download
				on:click={resume}
				class={buttonVariants({ variant: 'default', size: 'default' })}>Resume</a
			>
		</div>
	</div>
</Section>

// site/src/components/hero.tsx
import { BoxReveal } from "./magicui/box-reveal";
import { buttonVariants } from "./ui/button";
import Link from "next/link";
import { cn } from "~/lib/utils";
import { HighlightText } from "./highlight";
export default function Hero() {
  return (
    <div className="relative flex h-screen w-full flex-col items-center justify-center overflow-hidden">
      <div>
        <BoxReveal boxColor={"#5046e6"} duration={0.5}>
          <h2 className="text-left text-2xl">Hi I&apos;m</h2>
        </BoxReveal>
        <BoxReveal boxColor={"#5046e6"} duration={0.5}>
          <p className="text-[3.5rem] font-semibold">
            Xavier Loera Flores<HighlightText>.</HighlightText>
          </p>
        </BoxReveal>
      </div>
      <BoxReveal boxColor={"#5046e6"} duration={0.5}>
        <h2 className="mt-[.5rem] text-3xl font-bold">
          I am a <HighlightText>Software Engineer</HighlightText>
        </h2>
      </BoxReveal>

      <BoxReveal boxColor={"#5046e6"} duration={0.5}>
        <div className="mt-6">
          <p>
            -&gt; with 4 years of experience{" "}
            <HighlightText> building fullstack applications</HighlightText>
          </p>
        </div>
      </BoxReveal>

      <BoxReveal boxColor={"#5046e6"} duration={0.5}>
        <Link
          href="/files/resume.pdf"
          className={cn(
            buttonVariants({ variant: "default" }),
            "mt-[1.6rem] bg-[#5046e6]",
          )}
          target="_blank"
        >
          Resume
        </Link>
      </BoxReveal>
    </div>
  );
}
